<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * NuiteeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NuiteeRepository extends EntityRepository
{
}
